### ISSUE TITLE
Saw this on GitHub's LinkedIn

### ISSUE THREAD

**Issue by ahmedsajid** [oscarnevarezleal/gh-cms#15]
I think it's very cool.

**Comment by kangarooo** [comment]
Saw it in twitter, but i dont know if its cool, since its website showcase doesnt work.
Beeing in LinkedIn isnt a bug, but that the showcase doesnt work is a bug.
https://mobile.twitter.com/github/status/1466876903139254276
![image](https://user-images.githubusercontent.com/73187/144690655-6599c8fb-d619-4ba3-9b59-077757609e69.png)
